-- =============================================================================
-- Restaurant QR Ordering & Management System - Database Schema
-- Target: MySQL 8.0+
--
-- Design notes (read before editing):
--   * One restaurant per deployment (see Build Plan). `restaurant_id` is still
--     carried as an explicit FK column on every top-level entity (admin,
--     staff, category, food_item, restaurant_table, tax, discount, orders,
--     settings) rather than left implicit, so that adding a second restaurant
--     row later (multi-branch / multi-tenant) is a WHERE-clause change in the
--     DAO layer, not a schema rewrite.
--   * Strict child rows (food_image, order_item, qr_code, order_status_history,
--     payment) do NOT repeat restaurant_id - they always reach it by joining
--     through their parent, which keeps the schema normalized.
--   * order_item snapshots food_name_snapshot/unit_price at order time so a
--     later menu price change or item deletion never rewrites history.
--   * Inventory is intentionally NOT modeled yet. When it's added, it hangs
--     off food_item_id via new inventory_item / food_item_ingredient tables
--     without touching any column below (see comment on food_item).
--   * order_no / invoice_no are generated by the application (OrderNumberUtil /
--     InvoiceNumberUtil, Module 4) inside the same transaction as the INSERT,
--     not by MySQL - so they can be readable, prefixed, date-stamped codes
--     (e.g. ORD-20260703-0007) instead of raw auto-increment ids.
-- =============================================================================

CREATE DATABASE IF NOT EXISTS restaurant_db
    CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

USE restaurant_db;

SET FOREIGN_KEY_CHECKS = 0;

DROP TABLE IF EXISTS uploaded_file;
DROP TABLE IF EXISTS order_status_history;
DROP TABLE IF EXISTS payment;
DROP TABLE IF EXISTS order_item;
DROP TABLE IF EXISTS orders;
DROP TABLE IF EXISTS discount;
DROP TABLE IF EXISTS tax;
DROP TABLE IF EXISTS qr_code;
DROP TABLE IF EXISTS restaurant_table;
DROP TABLE IF EXISTS food_image;
DROP TABLE IF EXISTS food_item;
DROP TABLE IF EXISTS category;
DROP TABLE IF EXISTS settings;
DROP TABLE IF EXISTS staff;
DROP TABLE IF EXISTS admin;
DROP TABLE IF EXISTS restaurant;

SET FOREIGN_KEY_CHECKS = 1;

-- =============================================================================
-- restaurant: one row per deployment. Every field here is editable from
-- Admin > Settings at runtime - nothing in this table should ever require a
-- code change or redeploy to update.
-- =============================================================================
-- =============================================================================
-- uploaded_file: stores uploaded image bytes (logos, banners, category/food
-- photos, generated QR codes) in the database rather than on local disk, so
-- the app has no filesystem state and needs no persistent volume - every
-- other table already references these by the same "/uploads/<subdir>/<file>"
-- relative_path string a filesystem path would have used, so no other table
-- or DAO needed to change when this moved off disk.
-- =============================================================================
CREATE TABLE uploaded_file (
    file_id         INT AUTO_INCREMENT PRIMARY KEY,
    relative_path   VARCHAR(255)  NOT NULL,
    content_type    VARCHAR(100)  NOT NULL,
    data            LONGBLOB      NOT NULL,
    created_at      TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_uploadedfile_path UNIQUE (relative_path)
) ENGINE=InnoDB;

CREATE TABLE restaurant (
    restaurant_id           INT AUTO_INCREMENT PRIMARY KEY,
    name                    VARCHAR(150)  NOT NULL,
    logo_path               VARCHAR(255)  NULL,
    banner_path             VARCHAR(255)  NULL,
    address                 VARCHAR(500)  NULL,
    phone                   VARCHAR(20)   NULL,
    email                   VARCHAR(150)  NULL,
    gstin                   VARCHAR(20)   NULL,
    currency_code           VARCHAR(10)   NOT NULL DEFAULT 'INR',
    currency_symbol         VARCHAR(5)    NOT NULL DEFAULT '₹',
    service_charge_percent  DECIMAL(5,2)  NOT NULL DEFAULT 0.00,
    theme_color             VARCHAR(20)   NOT NULL DEFAULT '#c0392b',
    dark_mode_default       TINYINT(1)    NOT NULL DEFAULT 0,
    opening_time            TIME          NULL,
    closing_time            TIME          NULL,
    is_open                 TINYINT(1)    NOT NULL DEFAULT 1,
    created_at              TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at              TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB;

-- =============================================================================
-- admin: restaurant-owner login. Passwords are PBKDF2WithHmacSHA256 (see
-- com.restro.utility.PasswordUtil) - salt and hash stored separately,
-- never a raw or reversibly-encrypted password.
-- =============================================================================
CREATE TABLE admin (
    admin_id        INT AUTO_INCREMENT PRIMARY KEY,
    restaurant_id   INT NOT NULL,
    username        VARCHAR(50)   NOT NULL,
    password_hash   VARCHAR(255)  NOT NULL,
    password_salt   VARCHAR(255)  NOT NULL,
    full_name       VARCHAR(150)  NULL,
    email           VARCHAR(150)  NULL,
    is_active       TINYINT(1)    NOT NULL DEFAULT 1,
    last_login_at   TIMESTAMP     NULL,
    created_at      TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_admin_username UNIQUE (username),
    CONSTRAINT fk_admin_restaurant FOREIGN KEY (restaurant_id)
        REFERENCES restaurant (restaurant_id) ON DELETE CASCADE
) ENGINE=InnoDB;

-- =============================================================================
-- staff: kitchen/counter dashboard logins, created and role-assigned by the
-- admin. Role is a hard ENUM for the two dashboards that exist today; a
-- future full RBAC module (Future Enhancements) would add a permissions
-- table and could migrate this to a role_id FK without breaking existing rows.
-- =============================================================================
CREATE TABLE staff (
    staff_id        INT AUTO_INCREMENT PRIMARY KEY,
    restaurant_id   INT NOT NULL,
    username        VARCHAR(50)   NOT NULL,
    password_hash   VARCHAR(255)  NOT NULL,
    password_salt   VARCHAR(255)  NOT NULL,
    full_name       VARCHAR(150)  NULL,
    role            ENUM('KITCHEN','COUNTER') NOT NULL,
    phone           VARCHAR(20)   NULL,
    is_active       TINYINT(1)    NOT NULL DEFAULT 1,
    created_at      TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_staff_username UNIQUE (username),
    CONSTRAINT fk_staff_restaurant FOREIGN KEY (restaurant_id)
        REFERENCES restaurant (restaurant_id) ON DELETE CASCADE
) ENGINE=InnoDB;

-- =============================================================================
-- settings: generic key/value overflow for toggles that aren't worth a
-- dedicated restaurant column (e.g. kitchen notification sound on/off).
-- =============================================================================
CREATE TABLE settings (
    setting_id      INT AUTO_INCREMENT PRIMARY KEY,
    restaurant_id   INT NOT NULL,
    setting_key     VARCHAR(100)  NOT NULL,
    setting_value   VARCHAR(1000) NULL,
    CONSTRAINT uq_settings_restaurant_key UNIQUE (restaurant_id, setting_key),
    CONSTRAINT fk_settings_restaurant FOREIGN KEY (restaurant_id)
        REFERENCES restaurant (restaurant_id) ON DELETE CASCADE
) ENGINE=InnoDB;

-- =============================================================================
-- category: unlimited food categories, owner-orderable and toggle-able.
-- =============================================================================
CREATE TABLE category (
    category_id     INT AUTO_INCREMENT PRIMARY KEY,
    restaurant_id   INT NOT NULL,
    name            VARCHAR(100)  NOT NULL,
    display_order   INT           NOT NULL DEFAULT 0,
    image_path      VARCHAR(255)  NULL,
    is_active       TINYINT(1)    NOT NULL DEFAULT 1,
    created_at      TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT uq_category_restaurant_name UNIQUE (restaurant_id, name),
    CONSTRAINT fk_category_restaurant FOREIGN KEY (restaurant_id)
        REFERENCES restaurant (restaurant_id) ON DELETE CASCADE
) ENGINE=InnoDB;

-- =============================================================================
-- food_item: unlimited menu items. Inventory-ready: a future inventory_item
-- table + food_item_ingredient join table can reference food_item_id here
-- without altering a single column on this table.
-- =============================================================================
CREATE TABLE food_item (
    food_item_id      INT AUTO_INCREMENT PRIMARY KEY,
    restaurant_id     INT NOT NULL,
    category_id       INT NOT NULL,
    name              VARCHAR(150)  NOT NULL,
    description       VARCHAR(1000) NULL,
    ingredients       VARCHAR(1000) NULL,
    price             DECIMAL(10,2) NOT NULL,
    offer_price       DECIMAL(10,2) NULL,
    prep_time_minutes INT           NOT NULL DEFAULT 15,
    food_type         ENUM('VEG','NON_VEG','EGG') NOT NULL DEFAULT 'VEG',
    spice_level       ENUM('MILD','MEDIUM','HOT','EXTRA_HOT') NOT NULL DEFAULT 'MEDIUM',
    is_available      TINYINT(1)    NOT NULL DEFAULT 1,
    is_recommended    TINYINT(1)    NOT NULL DEFAULT 0,
    is_bestseller     TINYINT(1)    NOT NULL DEFAULT 0,
    display_order     INT           NOT NULL DEFAULT 0,
    created_at        TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at        TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT fk_fooditem_restaurant FOREIGN KEY (restaurant_id)
        REFERENCES restaurant (restaurant_id) ON DELETE CASCADE,
    CONSTRAINT fk_fooditem_category FOREIGN KEY (category_id)
        REFERENCES category (category_id) ON DELETE RESTRICT,
    INDEX idx_fooditem_category (category_id),
    INDEX idx_fooditem_available (restaurant_id, is_available)
) ENGINE=InnoDB;

-- =============================================================================
-- food_image: one-to-many so a food item can carry multiple photos without
-- widening food_item; is_primary marks the one shown on menu cards.
-- =============================================================================
CREATE TABLE food_image (
    food_image_id   INT AUTO_INCREMENT PRIMARY KEY,
    food_item_id    INT NOT NULL,
    image_path      VARCHAR(255) NOT NULL,
    is_primary      TINYINT(1)   NOT NULL DEFAULT 0,
    display_order   INT          NOT NULL DEFAULT 0,
    created_at      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_foodimage_fooditem FOREIGN KEY (food_item_id)
        REFERENCES food_item (food_item_id) ON DELETE CASCADE,
    INDEX idx_foodimage_fooditem (food_item_id)
) ENGINE=InnoDB;

-- =============================================================================
-- restaurant_table: physical tables. qr_token is a random opaque string
-- embedded in the printed QR URL (?table=<id>&token=<qr_token>) so table ids
-- aren't sequentially guessable/enumerable by a customer's phone browser.
-- =============================================================================
CREATE TABLE restaurant_table (
    table_id        INT AUTO_INCREMENT PRIMARY KEY,
    restaurant_id   INT NOT NULL,
    table_no        VARCHAR(20)  NOT NULL,
    capacity        INT          NOT NULL DEFAULT 4,
    qr_token        VARCHAR(64)  NOT NULL,
    is_active       TINYINT(1)   NOT NULL DEFAULT 1,
    created_at      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_table_restaurant_no UNIQUE (restaurant_id, table_no),
    CONSTRAINT uq_table_qr_token UNIQUE (qr_token),
    CONSTRAINT fk_table_restaurant FOREIGN KEY (restaurant_id)
        REFERENCES restaurant (restaurant_id) ON DELETE CASCADE
) ENGINE=InnoDB;

-- =============================================================================
-- qr_code: generated QR image per table, kept as its own table (not just a
-- column on restaurant_table) so regenerating a QR preserves history and the
-- exact target_url that was encoded is auditable even after settings change.
-- =============================================================================
CREATE TABLE qr_code (
    qr_code_id      INT AUTO_INCREMENT PRIMARY KEY,
    table_id        INT NOT NULL,
    image_path      VARCHAR(255) NOT NULL,
    target_url      VARCHAR(500) NOT NULL,
    generated_at    TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_qrcode_table FOREIGN KEY (table_id)
        REFERENCES restaurant_table (table_id) ON DELETE CASCADE,
    INDEX idx_qrcode_table (table_id)
) ENGINE=InnoDB;

-- =============================================================================
-- tax: named, percentage-based taxes (CGST/SGST/GST/VAT/...). Modeled as a
-- table rather than a single restaurant.tax_percent column so a restaurant
-- can configure more than one tax line on the bill without a schema change.
-- =============================================================================
CREATE TABLE tax (
    tax_id          INT AUTO_INCREMENT PRIMARY KEY,
    restaurant_id   INT NOT NULL,
    name            VARCHAR(50)  NOT NULL,
    percent         DECIMAL(5,2) NOT NULL,
    is_active       TINYINT(1)   NOT NULL DEFAULT 1,
    created_at      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_tax_restaurant FOREIGN KEY (restaurant_id)
        REFERENCES restaurant (restaurant_id) ON DELETE CASCADE
) ENGINE=InnoDB;

-- =============================================================================
-- discount: manual/coupon-style discounts. Usable today for a counter-applied
-- flat/percent discount; schema-ready for the future customer-facing coupon
-- code feature without alteration.
-- =============================================================================
CREATE TABLE discount (
    discount_id     INT AUTO_INCREMENT PRIMARY KEY,
    restaurant_id   INT NOT NULL,
    code            VARCHAR(30)  NOT NULL,
    description     VARCHAR(255) NULL,
    discount_type   ENUM('PERCENT','FLAT') NOT NULL DEFAULT 'PERCENT',
    value           DECIMAL(10,2) NOT NULL,
    is_active       TINYINT(1)   NOT NULL DEFAULT 1,
    valid_from      DATE NULL,
    valid_to        DATE NULL,
    created_at      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_discount_restaurant_code UNIQUE (restaurant_id, code),
    CONSTRAINT fk_discount_restaurant FOREIGN KEY (restaurant_id)
        REFERENCES restaurant (restaurant_id) ON DELETE CASCADE
) ENGINE=InnoDB;

-- =============================================================================
-- orders: one row per placed order. order_no is the human-facing code
-- (ORD-YYYYMMDD-NNNN) generated by the app in the same transaction as the
-- INSERT. Money columns are the authoritative, already-computed totals for
-- this order (never recalculated from order_item at display time), so a
-- later menu price change never rewrites a historical bill.
-- =============================================================================
CREATE TABLE orders (
    order_id                INT AUTO_INCREMENT PRIMARY KEY,
    restaurant_id           INT NOT NULL,
    order_no                VARCHAR(30) NOT NULL,
    table_id                INT NOT NULL,
    status                  ENUM('PENDING','ACCEPTED','PREPARING','READY','SERVED','COMPLETED','CANCELLED')
                                NOT NULL DEFAULT 'PENDING',
    subtotal                DECIMAL(10,2) NOT NULL DEFAULT 0.00,
    tax_amount              DECIMAL(10,2) NOT NULL DEFAULT 0.00,
    service_charge_amount   DECIMAL(10,2) NOT NULL DEFAULT 0.00,
    discount_amount         DECIMAL(10,2) NOT NULL DEFAULT 0.00,
    grand_total             DECIMAL(10,2) NOT NULL DEFAULT 0.00,
    discount_id             INT NULL,
    customer_note           VARCHAR(500) NULL,
    created_at              TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at              TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT uq_orders_order_no UNIQUE (order_no),
    CONSTRAINT fk_orders_restaurant FOREIGN KEY (restaurant_id)
        REFERENCES restaurant (restaurant_id) ON DELETE CASCADE,
    CONSTRAINT fk_orders_table FOREIGN KEY (table_id)
        REFERENCES restaurant_table (table_id) ON DELETE RESTRICT,
    CONSTRAINT fk_orders_discount FOREIGN KEY (discount_id)
        REFERENCES discount (discount_id) ON DELETE SET NULL,
    INDEX idx_orders_restaurant_status (restaurant_id, status),
    INDEX idx_orders_restaurant_created (restaurant_id, created_at),
    INDEX idx_orders_table (table_id)
) ENGINE=InnoDB;

-- =============================================================================
-- order_item: line items. food_name_snapshot + unit_price are copied at
-- order time so renaming/repricing/deleting a food item later never
-- corrupts a historical order.
-- =============================================================================
CREATE TABLE order_item (
    order_item_id         INT AUTO_INCREMENT PRIMARY KEY,
    order_id              INT NOT NULL,
    food_item_id          INT NOT NULL,
    food_name_snapshot     VARCHAR(150) NOT NULL,
    unit_price             DECIMAL(10,2) NOT NULL,
    quantity                INT NOT NULL,
    special_instructions    VARCHAR(300) NULL,
    line_total              DECIMAL(10,2) NOT NULL,
    created_at              TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_orderitem_order FOREIGN KEY (order_id)
        REFERENCES orders (order_id) ON DELETE CASCADE,
    CONSTRAINT fk_orderitem_fooditem FOREIGN KEY (food_item_id)
        REFERENCES food_item (food_item_id) ON DELETE RESTRICT,
    INDEX idx_orderitem_order (order_id),
    INDEX idx_orderitem_fooditem (food_item_id)
) ENGINE=InnoDB;

-- =============================================================================
-- order_status_history: append-only lifecycle trail (Pending -> Accepted ->
-- Preparing -> Ready -> Served -> Completed / Cancelled). Powers both the
-- customer-facing tracking timeline and report analytics (peak hours,
-- average prep duration) without recomputing from orders.updated_at alone.
-- =============================================================================
CREATE TABLE order_status_history (
    history_id            INT AUTO_INCREMENT PRIMARY KEY,
    order_id               INT NOT NULL,
    status                  ENUM('PENDING','ACCEPTED','PREPARING','READY','SERVED','COMPLETED','CANCELLED')
                                NOT NULL,
    changed_at              TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    changed_by_staff_id     INT NULL,
    CONSTRAINT fk_statushistory_order FOREIGN KEY (order_id)
        REFERENCES orders (order_id) ON DELETE CASCADE,
    CONSTRAINT fk_statushistory_staff FOREIGN KEY (changed_by_staff_id)
        REFERENCES staff (staff_id) ON DELETE SET NULL,
    INDEX idx_statushistory_order (order_id)
) ENGINE=InnoDB;

-- =============================================================================
-- payment: created only once an order is actually settled at the counter
-- (mark-paid action) - absence of a row for an order means "unpaid". One row
-- per order for this MVP; multi/partial payments would need a schema change
-- and are intentionally out of scope for v1.
-- =============================================================================
CREATE TABLE payment (
    payment_id       INT AUTO_INCREMENT PRIMARY KEY,
    order_id          INT NOT NULL,
    invoice_no        VARCHAR(30) NOT NULL,
    amount            DECIMAL(10,2) NOT NULL,
    method            ENUM('CASH','CARD','UPI','OTHER') NOT NULL DEFAULT 'CASH',
    payment_status    ENUM('PAID','REFUNDED') NOT NULL DEFAULT 'PAID',
    paid_at           TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_at        TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_payment_order UNIQUE (order_id),
    CONSTRAINT uq_payment_invoice_no UNIQUE (invoice_no),
    CONSTRAINT fk_payment_order FOREIGN KEY (order_id)
        REFERENCES orders (order_id) ON DELETE CASCADE
) ENGINE=InnoDB;
